# Generated by Django 4.0.5 on 2022-06-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clampmodel',
            name='cl_1',
            field=models.IntegerField(blank=True, verbose_name='Исходное'),
        ),
    ]
