# Generated by Django 4.0.5 on 2022-06-02 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0003_alter_clampmodel_cl_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reflowsectionmodel',
            name='r_4',
        ),
        migrations.AddField(
            model_name='reflowsectionmodel',
            name='reflow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reflow_section', to='programm.reflowparammodel', verbose_name='Параметры оплавления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reflowsectionmodel',
            name='r_0',
            field=models.FloatField(default=0.0, verbose_name='S'),
        ),
        migrations.AlterField(
            model_name='reflowsectionmodel',
            name='r_1',
            field=models.FloatField(default=0.0, verbose_name='Скорость вперёд'),
        ),
        migrations.AlterField(
            model_name='reflowsectionmodel',
            name='r_2',
            field=models.FloatField(default=0.0, verbose_name='Скорость назад'),
        ),
        migrations.AlterField(
            model_name='reflowsectionmodel',
            name='r_3',
            field=models.FloatField(default=0.0, verbose_name='U'),
        ),
    ]
