# Generated by Django 4.0.5 on 2022-06-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0004_remove_reflowsectionmodel_r_4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctorsectionmodel',
            name='c_4',
        ),
        migrations.AddField(
            model_name='correctorsectionmodel',
            name='corrector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='corrector_section', to='programm.correctorparammodel', verbose_name='Параметры корректора'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='correctorsectionmodel',
            name='c_0',
            field=models.FloatField(default=0.0, verbose_name='Ток коррекции'),
        ),
        migrations.AlterField(
            model_name='correctorsectionmodel',
            name='c_1',
            field=models.FloatField(default=0.0, verbose_name='Скорость вперёд'),
        ),
        migrations.AlterField(
            model_name='correctorsectionmodel',
            name='c_2',
            field=models.FloatField(default=0.0, verbose_name='Скорость назад'),
        ),
        migrations.AlterField(
            model_name='correctorsectionmodel',
            name='c_3',
            field=models.FloatField(default=0.0, verbose_name='Ток КЗ'),
        ),
    ]
