# Generated by Django 4.0.5 on 2022-06-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0006_programmmodel_max_diameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctorsectionmodel',
            name='section',
            field=models.IntegerField(default=0, verbose_name='Участок'),
        ),
        migrations.AddField(
            model_name='reflowsectionmodel',
            name='section',
            field=models.IntegerField(default=0, verbose_name='Участок'),
        ),
    ]
