# Generated by Django 4.0.5 on 2022-06-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0007_correctorsectionmodel_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherparametersensormodel',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='otherparametersensormodel',
            name='min_value',
        ),
    ]
